### ISSUE TITLE
Unable to get data from API

### ISSUE THREAD

**Issue by dhighe** [dhighe/Project-4-Deals#1]
Strangely enough, I am unable to get my data from my API. I have the proper URL from eBay but when I attempt to do the fetch from my node express server I do not get anything back from Postman. I get the following error in my terminal
 ```SyntaxError: Unexpected token / in JSON at position 0
    at Object.parse (native)
    at /Users/donaldhighe/code/wdi/project4/react-deals/node_modules/node-fetch/lib/body.js:48:15
    at process._tickCallback (internal/process/next_tick.js:103:7)B777
``` 
http://stackoverflow.com/questions/36814694/unexpected-token-in-json-at-position-4
This StackOverflow post stated that the issue could be related to how the data was being called, as it was not coming back as JSON, but in the URL I am using, I specified that the datatype as JSON
```
RESPONSE-DATA-FORMAT=JSON
```
I've looked into my API's documentation but I was able to figure out the issue. I've asked several classmates but they were unable to figure out the issue. 
http://developer.ebay.com/Devzone/finding/CallRef/findItemsByKeywords.html

**Comment by dhighe** [comment]
@trevorpreston
@gittheking
@jasonseminara
@rapala61
@irwintsay

**Comment by dhighe** [comment]
@mgershowitz

**Comment by gittheking** [comment]
@dhighe please include the code snippet for your `fetch` call so we can see if there is an error there.

**Comment by dhighe** [comment]
Here is my full fetch call from my back end, I've been conducting searches through postman, but I do not get any information back

```
const fetch = require('node-fetch');
const API_KEY = process.env.API_KEY;

function findProducts(req, res, next) {
  fetch(`https://svcs.ebay.com/services/search/FindingService/v1?SECURITY-APPNAME=${API_KEY}&OPERATION-NAME=findItemsByKeywords&SERVICE-VERSION=1.0.0&RESPONSE-DATA-FORMAT=JSON&callback=_cb_findItemsByKeywords&REST-PAYLOAD&keywords=${req.query.search}&paginationInput.entriesPerPage=6&GLOBAL-ID=EBAY-US&siteid=0`)
  .then(r => r.json())
  .then((data) => {
    res.products = data;
    next();
  })
  .catch((err) => {
    console.log(err);
    res.err = err;
    next();
  });
}

module.exports = {
  findProducts
};

```

**Comment by dhighe** [comment]
Irwin mentioned that APIs such as omdb has Access-Control-Allow-Origin:* in the Response Header, which allows you to fetch data without too much trouble. 
![screen shot 2016-12-13 at 9 34 39 am](https://cloud.githubusercontent.com/assets/20092541/21144337/40851086-c118-11e6-8da8-4bec4afdcde1.png)

The Ebay API, unfortunately, does not.
![screen shot 2016-12-13 at 9 34 25 am](https://cloud.githubusercontent.com/assets/20092541/21144393/73c0d138-c118-11e6-872c-a54cc7c2fa2b.png)

I tried to see if there was a way around this and it lead me to several repos regarding cors and ebays api, but they were geared towards XML
